# Generated by Django 6.0.1 on 2026-02-16 10:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('tmdb_id', models.IntegerField(primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('tmdb_id', models.IntegerField(primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('iso_code', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('tmdb_id', models.IntegerField(primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('tmdb_id', models.IntegerField(primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Movie_app.content')),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Дата выхода')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('poster_url', models.URLField(blank=True, validators=[django.core.validators.URLValidator()])),
                ('actors', models.ManyToManyField(to='Movie_app.actor', verbose_name='Актёры')),
                ('created_in', models.ManyToManyField(to='Movie_app.country', verbose_name='Страны производства')),
                ('director', models.ManyToManyField(to='Movie_app.director', verbose_name='Режиссёры')),
                ('genres', models.ManyToManyField(to='Movie_app.genre', verbose_name='Жанры')),
            ],
            options={
                'abstract': False,
            },
            bases=('Movie_app.content',),
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Movie_app.content')),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Дата выхода')),
                ('seasons', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('episodes', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('poster_url', models.URLField(blank=True, validators=[django.core.validators.URLValidator()])),
                ('actors', models.ManyToManyField(to='Movie_app.actor', verbose_name='Актёры')),
                ('created_in', models.ManyToManyField(to='Movie_app.country', verbose_name='Страны производства')),
                ('genres', models.ManyToManyField(to='Movie_app.genre', verbose_name='Жанры')),
            ],
            options={
                'abstract': False,
            },
            bases=('Movie_app.content',),
        ),
    ]
