# Generated by Django 6.0.1 on 2026-02-16 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Movie_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference_vector', models.JSONField(blank=True, null=True, verbose_name='Вектор предпочтений')),
                ('disliked_content', models.ManyToManyField(blank=True, related_name='disliked_by_user', to='Movie_app.content', verbose_name='Нелюбимый контент')),
                ('disliked_genres', models.ManyToManyField(blank=True, related_name='genres_disliked', to='Movie_app.genre', verbose_name='Нелюбимые жанры')),
                ('favorite_content', models.ManyToManyField(blank=True, related_name='favorites_by_user', to='Movie_app.content', verbose_name='Любимый контент')),
                ('favorite_genres', models.ManyToManyField(blank=True, related_name='genres_favorite', to='Movie_app.genre', verbose_name='Любимые жанры')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0, verbose_name='Оценка рекомендации')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='Movie_app.content')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-score'],
                'unique_together': {('user', 'content')},
            },
        ),
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('view', 'Просмотр'), ('like', 'Лайк'), ('dislike', 'Дизлайк'), ('rate', 'Рейтинг')], max_length=20, verbose_name='Тип взаимодействия')),
                ('rating', models.IntegerField(blank=True, null=True, verbose_name='Рейтинг (если применимо)')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='Movie_app.content')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'content', 'interaction_type')},
            },
        ),
    ]
